# Generated by Django 2.1.3 on 2019-01-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsave',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
